apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: my-channel-
  annotations:
    workflows.argoproj.io/description: |
      ''
    workflows.argoproj.io/version: '>= 3.1.0'
spec:
  serviceAccountName: argo
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
      - name: c8485b6c-7593-49f5-96ce-486e3528c887
        template: kafka-readerc8485b6c-7593-49f5-96ce-486e3528c887
        dependencies: []
      - name: d7ea1dc7-11c5-4280-88df-307f9b14c703
        template: s3-writerd7ea1dc7-11c5-4280-88df-307f9b14c703
        dependencies:
        - "c874ab87-d756-4fa6-bfdd-f40538e2770a"
        arguments:
          artifacts:
          - name: input
            from: "{{tasks.c874ab87-d756-4fa6-bfdd-f40538e2770a.outputs.artifacts.output}}"
      - name: e9de05c0-9bb7-41c3-aa87-7c8cfef57979
        template: sql-writere9de05c0-9bb7-41c3-aa87-7c8cfef57979
        dependencies:
        - "f73fd862-2540-4f38-b252-589a0a33af83"
        arguments:
          artifacts:
          - name: input
            from: "{{tasks.f73fd862-2540-4f38-b252-589a0a33af83.outputs.artifacts.output}}"
      - name: f73fd862-2540-4f38-b252-589a0a33af83
        template: validationf73fd862-2540-4f38-b252-589a0a33af83
        dependencies:
        - "c8485b6c-7593-49f5-96ce-486e3528c887"
        arguments:
          artifacts:
          - name: input
            from: "{{tasks.c8485b6c-7593-49f5-96ce-486e3528c887.outputs.artifacts.output}}"
      - name: c874ab87-d756-4fa6-bfdd-f40538e2770a
        template: optimizationc874ab87-d756-4fa6-bfdd-f40538e2770a
        dependencies:
        - "f73fd862-2540-4f38-b252-589a0a33af83"
        arguments:
          artifacts:
          - name: input
            from: "{{tasks.f73fd862-2540-4f38-b252-589a0a33af83.outputs.artifacts.output}}"
  - name: kafka-readerc8485b6c-7593-49f5-96ce-486e3528c887
    container:
      image: dorfa/aw-kafka-reader:latest
      command:
      - python
      args:
      - "main.py"
      env:
      - name: SERVERS
        value: "kafka.com"
      - name: SCHEMA
        value: "{}"
      - name: OUTPUT_FOLDER
        value: "/tmp/output/"
    outputs:
      artifacts:
      - name: output
        path: /tmp/output/
  - name: s3-writerd7ea1dc7-11c5-4280-88df-307f9b14c703
    container:
      image: dorfa/aw-s3-writer:latest
      command:
      - python
      args:
      - "main.py"
      env:
      - name: SERVERS
        value: "s3.com"
      - name: SCHEMA
        value: "{}"
      - name: INPUT_FOLDER
        value: "/tmp/input/"
    inputs:
      artifacts:
      - name: input
        path: /tmp/input/
  - name: sql-writere9de05c0-9bb7-41c3-aa87-7c8cfef57979
    container:
      image: dorfa/aw-sql-writer:latest
      command:
      - python
      args:
      - "main.py"
      env:
      - name: SERVERS
        value: "postgres.com"
      - name: SCHEMA
        value: "{}"
      - name: INPUT_FOLDER
        value: "/tmp/input/"
    inputs:
      artifacts:
      - name: input
        path: /tmp/input/
  - name: validationf73fd862-2540-4f38-b252-589a0a33af83
    container:
      image: dorfa/aw-validation:latest
      command:
      - python
      args:
      - "main.py"
      env:
      - name: SCHEMA
        value: "{}"
      - name: OUTPUT_FOLDER
        value: "/tmp/output/"
      - name: INPUT_FOLDER
        value: "/tmp/input/"
    inputs:
      artifacts:
      - name: input
        path: /tmp/input/
    outputs:
      artifacts:
      - name: output
        path: /tmp/output/
  - name: optimizationc874ab87-d756-4fa6-bfdd-f40538e2770a
    container:
      image: dorfa/aw-optimization:latest
      command:
      - python
      args:
      - "main.py"
      env:
      - name: SCHEMA
        value: "{}"
      - name: OUTPUT_FOLDER
        value: "/tmp/output/"
      - name: INPUT_FOLDER
        value: "/tmp/input/"
    inputs:
      artifacts:
      - name: input
        path: /tmp/input/
    outputs:
      artifacts:
      - name: output
        path: /tmp/output/
